[package]
name = "nucleus"
version = "0.1.0"
edition.workspace = true

[dependencies]
bytemuck = { workspace = true, features = ["derive"], optional = true }
curve = { workspace = true }

[features]
default = ["bytemuck"]
