[package]
name = "tokamak-nucleus"
version.workspace = true
edition.workspace = true

[dependencies]
# Workspace
curve = { workspace = true }
# External
bytemuck = { workspace = true, features = ["derive"], optional = true }

[features]
default = ["bytemuck"]
