[package]
name = "tokamak-ffi"
version.workspace = true
edition.workspace = true

[dependencies]
# Workspace
curve = { workspace = true }
nucleus = { workspace = true }
# External
flutter_rust_bridge = { version = "2.4", features = ["chrono"] }

[lib]
crate-type = ["cdylib", "rlib"]
