[package]
name = "tokamak-jet"
version.workspace = true
edition.workspace = true

[dependencies]
# Workspace
bytemuck = { workspace = true }
curve = { workspace = true }
nucleus = { workspace = true }
# External
flatbuffers = "24.3"
